=== exercism/problem-specifications/old-schema.json
{
   "comments":
   [ " This is a JSON Schema for 'canonical-data.json' files.     "
   , "                                                            "
   , " It enforces just a general structure for all exercises,    "
   , " without specifying how the test data should be organized   "
   , " for each type of test. We do this to keep generality and   "
   , " allow support for tests the do not fit well in the         "
   , " 'function (input) == output' structure, like property      "
   , " tests.                                                     "
   , "                                                            "
   , " The only thing enforced regarding how test data should be  "
   , " structured is the error encoding, because it was agreed    "
   , " and it doesn't restrict flexibility in a significant way.  "
   , "                                                            "
   , " Standardized property names may help when automatically    "
   , " deriving JSON parsers in some languages, so we followed    "
   , " a few conventions from the 'Google JSON Style Guide'.      "
   , "                                                            "
   , " Additionally, this schema strictly enforces letters, in    "
   , " lowerCamelCase, for naming the 'property' being tested. We "
   , " expect this regularity will allow an easier automatic      "
   , " generation of function's names in test generators,         "
   , " slightly reducing the amount of manually generated code.   "
   ],

   "$schema": "http://json-schema.org/draft-04/schema#",

   "self": { "vendor" : "io.exercism"
           , "name"   : "canonical-data"
           , "format" : "jsonschema"
           , "version": "1-0-0"
           },

   "$ref": "#/definitions/canonicalData",

   "definitions":{

      "canonicalData":
          { "description": "This is the top-level file structure"
          , "type"       : "object"
          , "required"   : ["exercise" , "version", "cases"]
          , "properties" :
                { "exercise" : { "$ref": "#/definitions/exercise"  }
                , "version"  : { "$ref": "#/definitions/version"   }
                , "comments" : { "$ref": "#/definitions/comments"  }
                , "cases"    : { "$ref": "#/definitions/testGroup" }
                }
          , "additionalProperties": false
          },

      "exercise":
          { "description": "Exercise's slug (kebab-case)"
          , "type"       : "string"
          , "pattern"    : "^[a-z]+(-[a-z]+)*$"
          },

      "version" :
          { "description" : "Semantic versioning: MAJOR.MINOR.PATCH"
          , "type"        : "string"
          , "pattern"     : "^(0|[1-9][0-9]*)(\\.(0|[1-9][0-9]*)){2}$"
          },

      "comments":
          { "description": "An array of strings to fake multi-line comments"
          , "type"       : "array"
          , "items"      : { "type": "string" }
          , "minItems"   : 1
          },

      "testGroup":
          { "description": "An array of labeled test items"
          , "type"       : "array"
          , "items"      : { "$ref": "#/definitions/labeledTestItem" }
          , "minItems"   : 1
          },

      "labeledTestItem":
          { "description": "A single test or group of tests with a description"
          , "oneOf": [ { "$ref": "#/definitions/labeledTest"      }
                     , { "$ref": "#/definitions/labeledTestGroup" }
                     ]
          },

      "labeledTest":
          { "description": "A single test with a description"
          , "type"       : "object"
          , "required"   : ["description", "property"]
          , "properties" :
                { "description": { "$ref": "#/definitions/description" }
                , "comments"   : { "$ref": "#/definitions/comments"    }
                , "property"   : { "$ref": "#/definitions/property"    }
                , "expected"   : { "$ref": "#/definitions/expected"    }
                }
          },

      "labeledTestGroup":
          { "description": "A group of tests with a description"
          , "type"       : "object"
          , "required"   : ["description", "cases"]
          , "properties" :
                { "description": { "$ref": "#/definitions/description" }
                , "comments"   : { "$ref": "#/definitions/comments"    }
                , "cases"      : { "$ref": "#/definitions/testGroup"   }
                }
          , "additionalProperties": false
          },

      "description":
          { "description": "A short, clear, one-line description"
          , "type"       : "string"
          },

      "property":
          { "description": "A letters-only, lowerCamelCase property name"
          , "type"       : "string"
          , "pattern"    : "^[a-z]+([A-Z][a-z]+)*[A-Z]?$"
          },

      "expected":
          { "description": "The expected return value of a test case"
          , "properties":
               { "error": { "$ref": "#/definitions/error" }
               }
          , "dependencies":
               { "error": { "maxProperties": 1 }
               }
          },

      "error":
          { "description": "A message describing an error condition"
          , "type"       : "string"
          }

    }

}

=== exercism/problem-specifications/exercises/dominoes/canonical-data.json
{
  "exercise": "dominoes",
  "version": "2.0.0",
  "comments": [
    "Inputs are given as lists of two-element lists.",
    "Feel free to convert the input to a sensible type in the specific language",
    "For example, if the target language has 2-tuples, that is a good candidate.",
    "",
    "There are two levels of this exercise that can be implemented and/or tested:",
    "",
    "1: Given a list of dominoes, determine whether it can be made into a chain.",
    "Under this scheme, the submitted code only needs to return a boolean.",
    "The test code only needs to check that that boolean value matches up.",
    "",
    "2: Given a list of dominoes, determine one possible chain, if one exists, or else conclude that none can be made.",
    "Under this scheme, the submitted code needs to either return a chain, or signal that none exists.",
    "Different languages may do this differently:",
    "return Option<Vector<Domino>>, return ([]Domino, error), raise exception, etc.",
    "The test code needs to check that the returned chain is correct (see below).",
    "",
    "It's infeasible to list every single possible result chain in this file.",
    "That's because for even a simple list [(1, 2), (2, 3), (3, 1)],",
    "the possible chains are that order, any rotation of that order,",
    "and any rotation of that order with all dominoes reversed.",
    "",
    "For this reason, this JSON file will only list whether a chain is possible.",
    "Tracks wishing to verify correct results of the second level must separately perform this verification.",
    "",
    "The properties to verify are:",
    "1. The submitted code claims there is a chain if and only if there actually is one.",
    "2. The number of dominoes in the output equals the number of dominoes in the input.",
    "3a. For each adjacent pair of dominoes ... (a, b), (c, d) ...: b is equal to c.",
    "3b. For the dominoes on the ends (a, b) ... (c, d): a is equal to d.",
    "4. Every domino appears in the output an equal number of times as the number of times it appears in the input.",
    "(in other words, the dominoes in the output are the same dominoes as the ones in the input)",
    "",
    "Feel free to examine the Rust track for ideas on implementing the second level verification."
  ],
  "cases": [
    {
      "description": "empty input = empty output",
      "property": "canChain",
      "input": [],
      "expected": true
    },
    {
      "description": "singleton input = singleton output",
      "property": "canChain",
      "input": [[1, 1]],
      "expected": true
    },
    {
      "description": "singleton that can't be chained",
      "property": "canChain",
      "input": [[1, 2]],
      "expected": false
    },
    {
      "description": "three elements",
      "property": "canChain",
      "input": [[1, 2], [3, 1], [2, 3]],
      "expected": true
    },
    {
      "description": "can reverse dominoes",
      "property": "canChain",
      "input": [[1, 2], [1, 3], [2, 3]],
      "expected": true
    },
    {
      "description": "can't be chained",
      "property": "canChain",
      "input": [[1, 2], [4, 1], [2, 3]],
      "expected": false
    },
    {
      "description": "disconnected - simple",
      "comments": [
        "This meets the requirement of being possibly-Euclidean.",
        "All vertices have even degree.",
        "Nevertheless, there is no chain here, as there's no way to get from 1 to 2.",
        "This test (and the two following) prevent solutions from using the even-degree test as the sole criterion,",
        "as that is not a sufficient condition."
      ],
      "property": "canChain",
      "input": [[1, 1], [2, 2]],
      "expected": false
    },
    {
      "description": "disconnected - double loop",
      "property": "canChain",
      "input": [[1, 2], [2, 1], [3, 4], [4, 3]],
      "expected": false
    },
    {
      "description": "disconnected - single isolated",
      "property": "canChain",
      "input": [[1, 2], [2, 3], [3, 1], [4, 4]],
      "expected": false
    },
    {
      "description": "need backtrack",
      "comments": [
        "Some solutions may make a chain out of (1, 2), (2, 3), (3, 1)",
        "then decide that since there are no more dominoes containing a 1,",
        "there is no chain possible.",
        "There is indeed a chain here, so this test checks for this line of reasoning.",
        "You need to place the (2, 4) after the (1, 2) rather than the (2, 3)."
      ],
      "property": "canChain",
      "input": [[1, 2], [2, 3], [3, 1], [2, 4], [2, 4]],
      "expected": true
    },
    {
      "description": "separate loops",
      "property": "canChain",
      "input": [[1, 2], [2, 3], [3, 1], [1, 1], [2, 2], [3, 3]],
      "expected": true
    },
    {
      "description": "nine elements",
      "property": "canChain",
      "input": [[1, 2], [5, 3], [3, 1], [1, 2], [2, 4], [1, 6], [2, 3], [3, 4], [5, 6]],
      "expected": true
    }
  ]
}

=== exercism/problem-specifications/exercises/pangram/canonical-data.json
{
  "exercise": "pangram",
  "comments": [
    "A pangram is a sentence using every letter of the alphabet at least once."
  ],
  "version": "1.2.0",
  "cases": [
    {
      "description": "checks if the given string is a pangram.",
      "comments": [
        "Output should be a boolean denoting if the string is a pangram or not."
      ],
      "cases": [
        {
          "description": "returns false for an empty message.",
          "property": "isPangram",
          "input": "",
          "expected": false
        },
        {
          "description": "returns false for an undefined/null message as argument.",
          "property": "isPangram",
          "input": null,
          "expected": false
        },
        {
          "description": "recognizes a perfect lower case pangram.",
          "property": "isPangram",
          "input": "abcdefghijklmnopqrstuvwxyz",
          "expected": true
        },
        {
          "description": "recognizes missing characters, e.g. 'x'.",
          "property": "isPangram",
          "input": "aquickmovementoftheenemywilljeopardizefivegunboats",
          "expected": false
        },
        {
          "description": "recognizes missing characters, e.g. 'h'.",
          "property": "isPangram",
          "input": "fiveboxingwizardsjumpquicklyatit",
          "expected": false
        },
        {
          "description": "recognizes an upper-case pangram.",
          "property": "isPangram",
          "input": "THEQUICKBROWNFOXJUMPSOVERTHELAZYDOG",
          "expected": true
        },
        {
          "description": "recognizes a missing character in upper-case, e.g. 'G'.",
          "property": "isPangram",
          "input": "THEQUICKBROWNFOXJUMPSOVERTHELAZYDOLL",
          "expected": false
        },
        {
          "description": "recognizes a mixed-case pangram.",
          "property": "isPangram",
          "input": "ThEFiVebOxInGWiZaRdSJuMpqUiCkLy",
          "expected": true
        },
        {
          "description": "recognizes a missing character in mixed-case, e.g. 'Y'.",
          "property": "isPangram",
          "input": "ThEFiVebOxInGWiZaRdSJuMpqUiCkL",
          "expected": false
        },
        {
          "description": "recognizes a pangram even if additional characters other than a-z are present.",
          "property": "isPangram",
          "input": "Victor_jagt-zwölf.B0xkämpfer >qu3r<über;den'großen\" Sylter#Deich!",
          "expected": true
        },
        {
          "description": "recognizes missing characters (e.g. 'd') even if additional characters other than a-z are present.",
          "property": "isPangram",
          "input": "Victor_jagt-zwölf.B0xkämpfer >qu3r< über;einen'großen\" Sylter#Teich!",
          "expected": false
        }
      ]
    }
  ]
}

=== exercism/problem-specifications/exercises/say/canonical-data.json
{
  "exercise": "say",
  "version": "1.0.0",
  "comments": [
    "Here -1 is used as expected value to indicate that the",
    "input value is out of the range described in the exercise."
  ],
  "cases": [
    {
      "description": "zero",
      "property": "say",
      "input": 0,
      "expected": "zero"
    },
    {
      "description": "one",
      "property": "say",
      "input": 1,
      "expected": "one"
    },
    {
      "description": "fourteen",
      "property": "say",
      "input": 14,
      "expected": "fourteen"
    },
    {
      "description": "twenty",
      "property": "say",
      "input": 20,
      "expected": "twenty"
    },
    {
      "description": "twenty-two",
      "property": "say",
      "input": 22,
      "expected": "twenty-two"
    },
    {
      "description": "one hundred",
      "property": "say",
      "input": 100,
      "expected": "one hundred"
    },
    {
      "description": "one hundred twenty-three",
      "property": "say",
      "input": 123,
      "expected": "one hundred twenty-three"
    },
    {
      "description": "one thousand",
      "property": "say",
      "input": 1000,
      "expected": "one thousand"
    },
    {
      "description": "one thousand two hundred thirty-four",
      "property": "say",
      "input": 1234,
      "expected": "one thousand two hundred thirty-four"
    },
    {
      "description": "eight hundred and ten thousand",
      "property": "say",
      "input": 810000,
      "expected": "eight hundred and ten thousand"
    },
    {
      "description": "one million",
      "property": "say",
      "input": 1000000,
      "expected": "one million"
    },
    {
      "description": "one million two thousand three hundred forty-five",
      "property": "say",
      "input": 1002345,
      "expected": "one million two thousand three hundred forty-five"
    },
    {
      "description": "one billion",
      "property": "say",
      "input": 1000000000,
      "expected": "one billion"
    },
    {
      "description": "a big number",
      "property": "say",
      "input": 987654321123,
      "expected": "nine hundred eighty-seven billion six hundred fifty-four million three hundred twenty-one thousand one hundred twenty-three"
    },
    {
      "description": "numbers below zero are out of range",
      "property": "say",
      "input": -1,
      "expected": -1
    },
    {
      "description": "numbers above 999,999,999,999 are out of range",
      "property": "say",
      "input": 1000000000000,
      "expected": -1
    }
  ]
}

=== exercism/problem-specifications/exercises/all-your-base/canonical-data.json
{
  "exercise": "all-your-base",
  "version": "2.0.0",
  "comments": [
    "It's up to each track do decide:",
    "",
    "1. What's the canonical representation of zero?",
    " - []? (if your track does this iff the input was empty, then follow if_your_track_translates_empty_to_empty)",
    " - [0]? (if your track does this, then follow if_your_track_outputs_zero_as_a_single_zero)",
    "",
    "2. What representations of zero are allowed?",
    " - []? (if your track allows this, then follow if_your_track_allows_empty_input_digits)",
    " - [0]? (if your track allows this, then follow if_your_track_allows_single_zero_as_input)",
    " - [0,0]? (if your track allows this, then follow if_your_track_allows_leading_zeroes_in_input)",
    "",
    "3. Are leading zeroes allowed?",
    "If so then follow if_your_track_allows_leading_zeroes_in_input",
    "",
    "4. How should invalid input be handled?",
    "",
    "All the undefined cases have objects under the `expected` key",
    "showing the different possible choices one can take.",
    "",
    "todo: one could imagine an explanation of the choices object",
    "",
    "All your numeric-base are belong to [2..]. :)"
  ],
  "cases": [
    {
      "description": "single bit one to decimal",
      "property": "rebase",
      "input_base": 2,
      "input_digits": [1],
      "output_base": 10,
      "expected": [1]
    },
    {
      "description": "binary to single decimal",
      "property": "rebase",
      "input_base": 2,
      "input_digits": [1, 0, 1],
      "output_base": 10,
      "expected": [5]
    },
    {
      "description": "single decimal to binary",
      "property": "rebase",
      "input_base": 10,
      "input_digits": [5],
      "output_base": 2,
      "expected": [1, 0, 1]
    },
    {
      "description": "binary to multiple decimal",
      "property": "rebase",
      "input_base": 2,
      "input_digits": [1, 0, 1, 0, 1, 0],
      "output_base": 10,
      "expected": [4, 2]
    },
    {
      "description": "decimal to binary",
      "property": "rebase",
      "input_base": 10,
      "input_digits": [4, 2],
      "output_base": 2,
      "expected": [1, 0, 1, 0, 1, 0]
    },
    {
      "description": "trinary to hexadecimal",
      "property": "rebase",
      "input_base": 3,
      "input_digits": [1, 1, 2, 0],
      "output_base": 16,
      "expected": [2, 10]
    },
    {
      "description": "hexadecimal to trinary",
      "property": "rebase",
      "input_base": 16,
      "input_digits": [2, 10],
      "output_base": 3,
      "expected": [1, 1, 2, 0]
    },
    {
      "description": "15-bit integer",
      "property": "rebase",
      "input_base": 97,
      "input_digits": [3, 46, 60],
      "output_base": 73,
      "expected": [6, 10, 45]
    },
    {
      "description": "empty list",
      "property": "rebase",
      "input_base": 2,
      "input_digits": [],
      "output_base": 10,
      "expected": {
        "choices": {
          "if_your_track_allows_empty_input_digits": {
            "choices": {
              "if_your_track_translates_empty_to_empty": [],
              "if_your_track_outputs_zero_as_a_single_zero": [0],
              "otherwise": []
            }
          },
          "otherwise": {"error": "input digits cannot be empty"}
        }
      }
    },
    {
      "description": "single zero",
      "property": "rebase",
      "input_base": 10,
      "input_digits": [0],
      "output_base": 2,
      "expected": {
        "choices": {
          "if_your_track_allows_single_zero_as_input": {
            "choices": {
              "if_your_track_outputs_zero_as_a_single_zero": [0],
              "otherwise": []
            }
          },
          "otherwise": {"error": "leading zeroes not allowed"}
        }
      }
    },
    {
      "description": "multiple zeros",
      "property": "rebase",
      "input_base": 10,
      "input_digits": [0, 0, 0],
      "output_base": 2,
      "expected": {
        "choices": {
          "if_your_track_allows_leading_zeroes_in_input": {
            "choices": {
              "if_your_track_outputs_zero_as_a_single_zero": [0],
              "otherwise": []
            }
          },
          "otherwise": {"error": "leading zeroes not allowed"}
        }
      }
    },
    {
      "description": "leading zeros",
      "property": "rebase",
      "input_base": 7,
      "input_digits": [0, 6, 0],
      "output_base": 10,
      "expected": {
        "choices": {
          "if_your_track_allows_leading_zeroes_in_input": [4, 2],
          "otherwise": {"error": "leading zeroes not allowed"}
        }
      }
    },
    {
      "description": "first base is one",
      "property": "rebase",
      "input_base": 1,
      "input_digits": [],
      "output_base": 10,
      "expected": null
    },
    {
      "description": "first base is zero",
      "property": "rebase",
      "input_base": 0,
      "input_digits": [],
      "output_base": 10,
      "expected": null
    },
    {
      "description": "first base is negative",
      "property": "rebase",
      "input_base": -2,
      "input_digits": [1],
      "output_base": 10,
      "expected": null
    },
    {
      "description": "negative digit",
      "property": "rebase",
      "input_base": 2,
      "input_digits": [1, -1, 1, 0, 1, 0],
      "output_base": 10,
      "expected": null
    },
    {
      "description": "invalid positive digit",
      "property": "rebase",
      "input_base": 2,
      "input_digits": [1, 2, 1, 0, 1, 0],
      "output_base": 10,
      "expected": null
    },
    {
      "description": "second base is one",
      "property": "rebase",
      "input_base": 2,
      "input_digits": [1, 0, 1, 0, 1, 0],
      "output_base": 1,
      "expected": null
    },
    {
      "description": "second base is zero",
      "property": "rebase",
      "input_base": 10,
      "input_digits": [7],
      "output_base": 0,
      "expected": null
    },
    {
      "description": "second base is negative",
      "property": "rebase",
      "input_base": 2,
      "input_digits": [1],
      "output_base": -7,
      "expected": null
    },
    {
      "description": "both bases are negative",
      "property": "rebase",
      "input_base": -2,
      "input_digits": [1],
      "output_base": -7,
      "expected": null
    }
  ]
}

=== exercism/problem-specifications/exercises/allergies/canonical-data.json
{
  "exercise": "allergies",
  "version": "1.2.1",
  "comments": [
    "Given a number and a substance, indicate whether Tom is allergic ",
    "to that substance.",
    "Test cases for this method involve more than one assertion.",
    "Each case in 'expected' specifies what the method should return for",
    "the given substance."
  ],
  "cases": [
    {
      "description": "no allergies means not allergic with:",
      "cases": [
        {
          "description": "peanuts",
          "property": "allergicTo",
          "input": {
            "item": "peanuts",
            "score": 0
          },
          "expected": false
        },
        {
          "description": "cats",
          "property": "allergicTo",
          "input": {
            "item": "cats",
            "score": 0
          },
          "expected": false
        },
        {
          "description": "strawberries",
          "property": "allergicTo",
          "input": {
            "item": "strawberries",
            "score": 0
          },
          "expected": false
        }
      ]
    },
    {
      "description": "allergic to only eggs",
      "property": "allergicTo",
      "input": {
        "item": "eggs",
        "score": 1
      },
      "expected": true
    },
    {
      "description": "allergic to eggs in addition to other stuff like:",
      "property": "allergicTo",
      "cases": [
        {
          "description": "eggs",
          "property": "allergicTo",
          "input": {
            "item": "eggs",
            "score": 5
          },
          "expected": true
        },
        {
          "description": "shellfish",
          "property": "allergicTo",
          "input": {
            "item": "shellfish",
            "score": 5
          },
          "expected": true
        },
        {
          "description": "strawberries",
          "property": "allergicTo",
          "input": {
            "item": "strawberries",
            "score": 5
          },
          "expected": false
        }
      ]
    },
    {
      "description": "allergic to strawberries but not peanuts with:",
      "property": "allergicTo",
      "input": {
        "score": 9
      },
      "cases": [
        {
          "description": "eggs",
          "property": "allergicTo",
          "input": {
            "item": "eggs",
            "score": 9
          },
          "expected": true
        },
        {
          "description": "peanuts",
          "property": "allergicTo",
          "input": {
            "item": "peanuts",
            "score": 9
          },
          "expected": false
        },
        {
          "description": "shellfish",
          "property": "allergicTo",
          "input": {
            "item": "shellfish",
            "score": 9
          },
          "expected": false
        },
        {
          "description": "strawberries",
          "property": "allergicTo",
          "input": {
            "item": "strawberries",
            "score": 9
          },
          "expected": true
        }
      ]
    },
    {
      "description": "list when:",
      "comments": [
        "Given a number, list all things Tom is allergic to"
      ],
      "cases": [
        {
          "description": "no allergies",
          "property": "list",
          "input": {
            "score": 0
          },
          "expected": []
        },
        {
          "description": "just eggs",
          "property": "list",
          "input": {
            "score": 1
          },
          "expected": [
            "eggs"
          ]
        },
        {
          "description": "just peanuts",
          "property": "list",
          "input": {
            "score": 2
          },
          "expected": [
            "peanuts"
          ]
        },
        {
          "description": "just strawberries",
          "property": "list",
          "input": {
            "score": 8
          },
          "expected": [
            "strawberries"
          ]
        },
        {
          "description": "eggs and peanuts",
          "property": "list",
          "input": {
            "score": 3
          },
          "expected": [
            "eggs",
            "peanuts"
          ]
        },
        {
          "description": "more than eggs but not peanuts",
          "property": "list",
          "input": {
            "score": 5
          },
          "expected": [
            "eggs",
            "shellfish"
          ]
        },
        {
          "description": "lots of stuff",
          "property": "list",
          "input": {
            "score": 248
          },
          "expected": [
            "strawberries",
            "tomatoes",
            "chocolate",
            "pollen",
            "cats"
          ]
        },
        {
          "description": "everything",
          "property": "list",
          "input": {
            "score": 255
          },
          "expected": [
            "eggs",
            "peanuts",
            "shellfish",
            "strawberries",
            "tomatoes",
            "chocolate",
            "pollen",
            "cats"
          ]
        },
        {
          "description": "no allergen score parts",
          "property": "list",
          "input": {
            "score": 509
          },
          "expected": [
            "eggs",
            "shellfish",
            "strawberries",
            "tomatoes",
            "chocolate",
            "pollen",
            "cats"
          ]
        }
      ]
    }
  ]
}
