=== exercism/problem-specifications/old-schema.json
{
   "comments":
   [ " This is a JSON Schema for 'canonical-data.json' files.     "
   , "                                                            "
   , " It enforces just a general structure for all exercises,    "
   , " without specifying how the test data should be organized   "
   , " for each type of test. We do this to keep generality and   "
   , " allow support for tests the do not fit well in the         "
   , " 'function (input) == output' structure, like property      "
   , " tests.                                                     "
   , "                                                            "
   , " The only thing enforced regarding how test data should be  "
   , " structured is the error encoding, because it was agreed    "
   , " and it doesn't restrict flexibility in a significant way.  "
   , "                                                            "
   , " Standardized property names may help when automatically    "
   , " deriving JSON parsers in some languages, so we followed    "
   , " a few conventions from the 'Google JSON Style Guide'.      "
   , "                                                            "
   , " Additionally, this schema strictly enforces letters, in    "
   , " lowerCamelCase, for naming the 'property' being tested. We "
   , " expect this regularity will allow an easier automatic      "
   , " generation of function's names in test generators,         "
   , " slightly reducing the amount of manually generated code.   "
   ],

   "$schema": "http://json-schema.org/draft-04/schema#",

   "self": { "vendor" : "io.exercism"
           , "name"   : "canonical-data"
           , "format" : "jsonschema"
           , "version": "1-0-0"
           },

   "$ref": "#/definitions/canonicalData",

   "definitions":{

      "canonicalData":
          { "description": "This is the top-level file structure"
          , "type"       : "object"
          , "required"   : ["exercise" , "version", "cases"]
          , "properties" :
                { "exercise" : { "$ref": "#/definitions/exercise"  }
                , "version"  : { "$ref": "#/definitions/version"   }
                , "comments" : { "$ref": "#/definitions/comments"  }
                , "cases"    : { "$ref": "#/definitions/testGroup" }
                }
          , "additionalProperties": false
          },

      "exercise":
          { "description": "Exercise's slug (kebab-case)"
          , "type"       : "string"
          , "pattern"    : "^[a-z]+(-[a-z]+)*$"
          },

      "version" :
          { "description" : "Semantic versioning: MAJOR.MINOR.PATCH"
          , "type"        : "string"
          , "pattern"     : "^(0|[1-9][0-9]*)(\\.(0|[1-9][0-9]*)){2}$"
          },

      "comments":
          { "description": "An array of strings to fake multi-line comments"
          , "type"       : "array"
          , "items"      : { "type": "string" }
          , "minItems"   : 1
          },

      "testGroup":
          { "description": "An array of labeled test items"
          , "type"       : "array"
          , "items"      : { "$ref": "#/definitions/labeledTestItem" }
          , "minItems"   : 1
          },

      "labeledTestItem":
          { "description": "A single test or group of tests with a description"
          , "oneOf": [ { "$ref": "#/definitions/labeledTest"      }
                     , { "$ref": "#/definitions/labeledTestGroup" }
                     ]
          },

      "labeledTest":
          { "description": "A single test with a description"
          , "type"       : "object"
          , "required"   : ["description", "property"]
          , "properties" :
                { "description": { "$ref": "#/definitions/description" }
                , "comments"   : { "$ref": "#/definitions/comments"    }
                , "property"   : { "$ref": "#/definitions/property"    }
                , "expected"   : { "$ref": "#/definitions/expected"    }
                }
          },

      "labeledTestGroup":
          { "description": "A group of tests with a description"
          , "type"       : "object"
          , "required"   : ["description", "cases"]
          , "properties" :
                { "description": { "$ref": "#/definitions/description" }
                , "comments"   : { "$ref": "#/definitions/comments"    }
                , "cases"      : { "$ref": "#/definitions/testGroup"   }
                }
          , "additionalProperties": false
          },

      "description":
          { "description": "A short, clear, one-line description"
          , "type"       : "string"
          },

      "property":
          { "description": "A letters-only, lowerCamelCase property name"
          , "type"       : "string"
          , "pattern"    : "^[a-z]+([A-Z][a-z]+)*[A-Z]?$"
          },

      "expected":
          { "description": "The expected return value of a test case"
          , "properties":
               { "error": { "$ref": "#/definitions/error" }
               }
          , "dependencies":
               { "error": { "maxProperties": 1 }
               }
          },

      "error":
          { "description": "A message describing an error condition"
          , "type"       : "string"
          }

    }

}

=== exercism/problem-specifications/exercises/nucleotide-count/canonical-data.json
{
  "exercise": "nucleotide-count",
  "comments": [
    "Given a string of nucleotides, the count of each nucleotide is returned."
  ],
  "version": "1.1.0",
  "cases": [
    {
      "description": "counts all nucleotides in a provided strand.",
      "comments": [
        "nucleotideCounts counts all DNA-nucleotides in the input strand and returns an object with properties",
        "A, C, G and T holding their respective amounts."
      ],
      "cases": [
        {
          "description": "returns zeroes in case of an empty input strand.",
          "property": "nucleotideCounts",
          "strand": "",
          "expected": {
            "A": 0,
            "C": 0,
            "G": 0,
            "T": 0
          }
        },
        {
          "comments" : [
            "Should check for null-references and assume an empty input."
          ],
          "description": "returns zeroes for an undefined/null strand as argument.",
          "property": "nucleotideCounts",
          "strand": null,
          "expected": {
            "A": 0,
            "C": 0,
            "G": 0,
            "T": 0
          }
        },
        {
          "description": "returns the counts of nucleotides in a single-character input.",
          "property": "nucleotideCounts",
          "strand": "G",
          "expected": {
            "A": 0,
            "C": 0,
            "G": 1,
            "T": 0
          }
        },
        {
          "description": "returns the counts of nucleotides in a strand containing one repeated nucleotide.",
          "property": "nucleotideCounts",
          "strand": "GGGGGGG",
          "expected": {
            "A": 0,
            "C": 0,
            "G": 7,
            "T": 0
          }
        },
        {
          "description": "returns the count of nucleotides in a strand containing all nucleotides.",
          "property": "nucleotideCounts",
          "strand": "AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC",
          "expected": {
            "A": 20,
            "C": 12,
            "G": 17,
            "T": 21
          }
        },
        {
          "description": "returns the count of nucleotides in a strand containing mixed-case nucleotides.",
          "property": "nucleotideCounts",
          "strand": "aGcTtTtCaTtCtGaCtGcAaCgGgCaAtAtGtCtCtGtGtGgAtTaAaAaAaGaGtGtCtGaTaGcAgC",
          "expected": {
            "A": 20,
            "C": 12,
            "G": 17,
            "T": 21
          }
        },
        {
          "comments" : [
            "This should call the property/function at least two times and check if it returns the same",
            "result. This prevents errors where the call aggregates (sums up) the counts of each call."
          ],
          "description": "returns the same amounts for consecutive nucleotideCounts calls.",
          "property": "nucleotideCounts",
          "strand": "AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC",
          "expected" : true
        },
        {
          "description": "handles incorrect inputs.",
          "cases": [
            {
              "description": "throws error if DNA input does not include anything but ACGT-characters.",
              "property": "nucleotideCounts",
              "strand": "AGUUÃ„1+ :'A'}CT",
              "expected": {
                "error": "Invalid nucleotide in strand"
              }
            }
          ]
        }
      ]
    }
  ]
}

=== exercism/problem-specifications/exercises/armstrong-numbers/canonical-data.json
{
  "exercise": "armstrong-number",
  "version": "1.0.0",
  "comments": [
    "Both input-parameters are always given in base-10(decimal)."
  ],
  "cases": [
    {
      "description": "0 is an Armstrong number in base 10",
      "property": "armstrong",
      "input": {
        "number": 0,
        "base": 10
      },
      "expected": true
    },
    {
      "description": "1 is an Armstrong number in base 10",
      "property": "armstrong",
      "input": {
        "number": 1,
        "base": 10
      },
      "expected": true
    },
    {
      "description": "2 is an Armstrong number in base 10",
      "property": "armstrong",
      "input": {
        "number": 2,
        "base": 10
      },
      "expected": true
    },
    {
      "description": "9 is an Armstrong number in base 10",
      "property": "armstrong",
      "input": {
        "number": 9,
        "base": 10
      },
      "expected": true
    },
    {
      "description": "10 is not an Armstrong number in base 10",
      "property": "armstrong",
      "input": {
        "number": 10,
        "base": 10
      },
      "expected": false
    },
    {
      "description": "100 is not an Armstrong number in base 10",
      "property": "armstrong",
      "input": {
        "number": 100,
        "base": 10
      },
      "expected": false
    },
    {
      "description": "111 is not an Armstrong number in base 10",
      "property": "armstrong",
      "input": {
        "number": 111,
        "base": 10
      },
      "expected": false
    },
    {
      "description": "153 is an Armstrong number in base 10",
      "property": "armstrong",
      "input": {
        "number": 153,
        "base": 10
      },
      "expected": true
    },
    {
      "description": "370 is an Armstrong number in base 10",
      "property": "armstrong",
      "input": {
        "number": 370,
        "base": 10
      },
      "expected": true
    },
    {
      "description": "9474 is an Armstrong number in base 10",
      "property": "armstrong",
      "input": {
        "number": 9474,
        "base": 10
      },
      "expected": true
    },
    {
      "description": "0 is an Armstrong number in base 8",
      "property": "armstrong",
      "input": {
        "number": 0,
        "base": 8
      },
      "expected": true
    },
    {
      "description": "1 is an Armstrong number in base 8",
      "property": "armstrong",
      "input": {
        "number": 1,
        "base": 8
      },
      "expected": true
    },
    {
      "description": "2 is an Armstrong number in base 8",
      "property": "armstrong",
      "input": {
        "number": 2,
        "base": 8
      },
      "expected": true
    },
    {
      "description": "7 is an Armstrong number in base 8",
      "property": "armstrong",
      "input": {
        "number": 7,
        "base": 8
      },
      "expected": true
    },
    {
      "description": "10 is not an Armstrong number in base 8",
      "property": "armstrong",
      "input": {
        "number": 10,
        "base": 8
      },
      "expected": false
    },
    {
      "description": "432 is an Armstrong number in base 8",
      "property": "armstrong",
      "input": {
        "number": 432,
        "base": 8
      },
      "expected": true
    },
    {
      "description": "2 is an Armstrong number in base 3",
      "property": "armstrong",
      "input": {
        "number": 2,
        "base": 3
      },
      "expected": true
    },
    {
      "description": "4 is not an Armstrong number in base 3",
      "property": "armstrong",
      "input": {
        "number": 4,
        "base": 3
      },
      "expected": false
    },
    {
      "description": "17 is an Armstrong number in base 3",
      "property": "armstrong",
      "input": {
        "number": 17,
        "base": 3
      },
      "expected": true
    },
    {
      "description": "10 is an Armstrong number in base 16",
      "property": "armstrong",
      "input": {
        "number": 10,
        "base": 16
      },
      "expected": true
    },
    {
      "description": "10 is not an Armstrong number in base 3",
      "property": "armstrong",
      "input": {
        "number": 10,
        "base": 3
      },
      "expected": false
    }
  ]
}

=== exercism/problem-specifications/exercises/diamond/canonical-data.json
{
    "exercise": "diamond",
    "version": "1.0.0",
    "comments": [
        " The tests contained within this canonical data file are suitable   ",
        " for value-based testing, in which each test case checks that the   ",
        " value returned by the function under test is in every way          ",
        " identical to a given expected value.                               ",
        "                                                                    ",
        " This exercise is also amenable to property-based testing, in which ",
        " each test case verifies that the value returned by the function    ",
        " under test exhibits a specific desired property.                   ",
        "                                                                    ",
        " Several tracks (notably, C# and Go) forgo the value-based tests    ",
        " below in favor of property-based tests. If you are feeling         ",
        " adventurous and would like to use this exercise to introduce the   ",
        " concept of property-based testing to participants in your track,   ",
        " please ignore the value-based tests below and instead reference    ",
        " the test suites in the aforementioned tracks.                      "
    ],
    "cases": [
        {
            "description": "Degenerate case with a single 'A' row",
            "property": "rows",
            "input": "A",
            "expected": [
                "A"
            ]
        },
        {
            "description": "Degenerate case with no row containing 3 distinct groups of spaces",
            "property": "rows",
            "input": "B",
            "expected": [
                " A ",
                "B B",
                " A "
            ]
        },
        {
            "description": "Smallest non-degenerate case with odd diamond side length",
            "property": "rows",
            "input": "C",
            "expected": [
                "  A  ",
                " B B ",
                "C   C",
                " B B ",
                "  A  "
            ]
        },
        {
            "description": "Smallest non-degenerate case with even diamond side length",
            "property": "rows",
            "input": "D",
            "expected": [
                "   A   ",
                "  B B  ",
                " C   C ",
                "D     D",
                " C   C ",
                "  B B  ",
                "   A   "
            ]
        },
        {
            "description": "Largest possible diamond",
            "property": "rows",
            "input": "Z",
            "expected": [
                "                         A                         ",
                "                        B B                        ",
                "                       C   C                       ",
                "                      D     D                      ",
                "                     E       E                     ",
                "                    F         F                    ",
                "                   G           G                   ",
                "                  H             H                  ",
                "                 I               I                 ",
                "                J                 J                ",
                "               K                   K               ",
                "              L                     L              ",
                "             M                       M             ",
                "            N                         N            ",
                "           O                           O           ",
                "          P                             P          ",
                "         Q                               Q         ",
                "        R                                 R        ",
                "       S                                   S       ",
                "      T                                     T      ",
                "     U                                       U     ",
                "    V                                         V    ",
                "   W                                           W   ",
                "  X                                             X  ",
                " Y                                               Y ",
                "Z                                                 Z",
                " Y                                               Y ",
                "  X                                             X  ",
                "   W                                           W   ",
                "    V                                         V    ",
                "     U                                       U     ",
                "      T                                     T      ",
                "       S                                   S       ",
                "        R                                 R        ",
                "         Q                               Q         ",
                "          P                             P          ",
                "           O                           O           ",
                "            N                         N            ",
                "             M                       M             ",
                "              L                     L              ",
                "               K                   K               ",
                "                J                 J                ",
                "                 I               I                 ",
                "                  H             H                  ",
                "                   G           G                   ",
                "                    F         F                    ",
                "                     E       E                     ",
                "                      D     D                      ",
                "                       C   C                       ",
                "                        B B                        ",
                "                         A                         "
            ]
        }
    ]
}

=== exercism/problem-specifications/exercises/darts/canonical-data.json
{
  "exercise": "darts",
  "version": "2.1.0",
  "comments": [
    "Return the correct amount earned by a dart landing in a given point in the target."
  ],
  "cases": [
    {
      "property": "score",
      "description": "Missed target",
      "input": {
        "x": -9,
        "y": 9
      },
      "expected": 0
    },
    {
      "property": "score",
      "description": "On outer circle",
      "input": {
        "x": 0,
        "y": 10
      },
      "expected": 1
    },
    {
      "property": "score",
      "description": "On middle circle",
      "input": {
        "x": -5,
        "y": 0
      },
      "expected": 5
    },
    {
      "property": "score",
      "description": "On inner circle",
      "input": {
        "x": 0,
        "y": -1
      },
      "expected": 10
    },
    {
      "property": "score",
      "description": "Near centre",
      "input": {
        "x": -0.1,
        "y": -0.1
      },
      "expected": 10
    },
    {
      "property": "score",
      "description": "Just within inner circle",
      "input": {
        "x": 0.7,
        "y": 0.7
      },
      "expected": 10
    },
    {
      "property": "score",
      "description": "Just beyond inner circle",
      "input": {
        "x": 0.8,
        "y": -0.8
      },
      "expected": 5
    },
    {
      "property": "score",
      "description": "Just within middle circle",
      "input": {
        "x": -3.5,
        "y": 3.5
      },
      "expected": 5
    },   
    {
      "property": "score",
      "description": "Just beyond middle circle",
      "input": {
        "x": -3.6,
        "y": -3.6
      },
      "expected": 1
    },     
    {
      "property": "score",
      "description": "Just within outer circle",
      "input": {
        "x": -7.0,
        "y": 7.0
      },
      "expected": 1
    },     
    {
      "property": "score",
      "description": "Just beyond outer circle",
      "input": {
        "x": 7.1,
        "y": -7.1
      },
      "expected": 0
    },    
    {
      "property": "score",
      "description": "Asymmetric position between inner and middle circles",
      "input": {
        "x": 0.5,
        "y": -4
      },
      "expected": 5
    }
  ]
}

=== exercism/problem-specifications/exercises/little-schemer/canonical-data.json
{
  "exercise": "little-schemer",
  "version": "1.0.0",
  "comments": [
    "Tests are ordered to allow sequential build up of primitives",
    "for use in writing the final recursive function lat?."
  ],
  "cases": [
    {
      "description": "Test null? of a list",
      "cases": [
        {
          "description": "null of non-empty list",
          "property": "boolean",
          "input": {
            "function": "null?",
            "list": [1]
          },
          "expected": false
        },
        {
          "description": "null of empty list",
          "property": "boolean",
          "input": {
            "function": "null?",
            "list": []
          },
          "expected": true
        },
        {
          "description": "null of non-list",
          "property": "exception",
          "input": {
            "function": "null?",
            "list": "'Zang'"
          },
          "comments": [
            "The primitive null? is defined only for lists."
          ],
          "expected": -1
        }
      ]
    },
    {
      "description": "Test car of a list",
      "cases": [
        {
          "description": "car of simple list",
          "property": "equality",
          "input": {
            "function": "car",
            "list": [1]
          },
          "expected": 1
        },
        {
          "description": "car of small list",
          "property": "equality",
          "input": {
            "function": "car",
            "list": ["Immaculate", 23, "G.O.A.T"]
          },
          "expected": "'Immaculate'"
        },
        {
          "description": "car of nested list",
          "property": "equality",
          "input": {
            "function": "car",
            "list": [[4, 5], 6, 7, [8, 9]]
          },
          "expected": [4, 5]
        },
        {
          "description": "car of null list",
          "property": "exception",
          "input": {
            "function": "car",
            "list": []
          },
          "comments": [
            "The primitive car is defined only for non-empty lists."
          ],
          "expected": -1
        }
      ]
    },
    {
      "description": "Test cdr of a list",
      "cases": [
        {
          "description": "cdr of simple list",
          "property": "equality",
          "input": {
            "function": "cdr",
            "list": [1]
          },
          "expected": []
        },
        {
          "description": "cdr of small list",
          "property": "equality",
          "input": {
            "function": "cdr",
            "list": ["Immaculate", 23, "G.O.A.T"]
          },
          "expected": [23, "G.O.A.T"]
        },
        {
          "description": "cdr of nested list",
          "property": "equality",
          "input": {
            "function": "cdr",
            "list": [[4, 5], 6, 7, [8, 9]]
          },
          "expected": [6, 7, [8, 9]]
        },
        {
          "description": "cdr of null list",
          "property": "exception",
          "input": {
            "function": "cdr",
            "list": []
          },
          "comments": [
            "The primitive cdr is defined only for non-empty lists. The cdr of any non-empty list is always another list"
          ],
          "expected": -1
        }
      ]
    },
    {
      "description": "Test atom of a list",
      "cases": [
        {
          "description": "atom of a list",
          "property": "boolean",
          "input": {
            "function": "atom?",
            "list": ["Immaculate", 23]
          },
          "expected": false
        },
        {
          "description": "atom of a string",
          "property": "boolean",
          "input": {
            "function": "atom?",
            "list": "'Immaculate'"
          },
          "expected": true
        },
        {
          "description": "atom of an integer",
          "property": "boolean",
          "input": {
            "function": "atom?",
            "list": 23
          },
          "expected": true
        },
        {
          "description": "atom of null list",
          "property": "boolean",
          "input": {
            "function": "atom?",
            "list": []
          },
          "expected": false
        }
      ]
    },
    {
      "description": "Test lat of a list",
      "cases": [
        {
          "description": "lat of a simple list",
          "property": "boolean",
          "input": {
            "function": "lat?",
            "list": ["Immaculate", 23]
          },
          "expected": true
        },
        {
          "description": "lat of another list",
          "property": "boolean",
          "input": {
            "function": "lat?",
            "list": ["Immaculate", "Bicycle"]
          },
          "expected": true
        },
        {
          "description": "lat of nested list",
          "property": "boolean",
          "input": {
            "function": "lat?",
            "list": ["Help", "I", "am", ["nested"]]
          },
          "expected": false
        },
        {
          "description": "lat of null list",
          "property": "boolean",
          "input": {
            "function": "lat?",
            "list": []
          },
          "expected": true
        }
      ]
    }
  ]
}
