=== exercism/problem-specifications/old-schema.json
{
   "comments":
   [ " This is a JSON Schema for 'canonical-data.json' files.     "
   , "                                                            "
   , " It enforces just a general structure for all exercises,    "
   , " without specifying how the test data should be organized   "
   , " for each type of test. We do this to keep generality and   "
   , " allow support for tests the do not fit well in the         "
   , " 'function (input) == output' structure, like property      "
   , " tests.                                                     "
   , "                                                            "
   , " The only thing enforced regarding how test data should be  "
   , " structured is the error encoding, because it was agreed    "
   , " and it doesn't restrict flexibility in a significant way.  "
   , "                                                            "
   , " Standardized property names may help when automatically    "
   , " deriving JSON parsers in some languages, so we followed    "
   , " a few conventions from the 'Google JSON Style Guide'.      "
   , "                                                            "
   , " Additionally, this schema strictly enforces letters, in    "
   , " lowerCamelCase, for naming the 'property' being tested. We "
   , " expect this regularity will allow an easier automatic      "
   , " generation of function's names in test generators,         "
   , " slightly reducing the amount of manually generated code.   "
   ],

   "$schema": "http://json-schema.org/draft-04/schema#",

   "self": { "vendor" : "io.exercism"
           , "name"   : "canonical-data"
           , "format" : "jsonschema"
           , "version": "1-0-0"
           },

   "$ref": "#/definitions/canonicalData",

   "definitions":{

      "canonicalData":
          { "description": "This is the top-level file structure"
          , "type"       : "object"
          , "required"   : ["exercise" , "version", "cases"]
          , "properties" :
                { "exercise" : { "$ref": "#/definitions/exercise"  }
                , "version"  : { "$ref": "#/definitions/version"   }
                , "comments" : { "$ref": "#/definitions/comments"  }
                , "cases"    : { "$ref": "#/definitions/testGroup" }
                }
          , "additionalProperties": false
          },

      "exercise":
          { "description": "Exercise's slug (kebab-case)"
          , "type"       : "string"
          , "pattern"    : "^[a-z]+(-[a-z]+)*$"
          },

      "version" :
          { "description" : "Semantic versioning: MAJOR.MINOR.PATCH"
          , "type"        : "string"
          , "pattern"     : "^(0|[1-9][0-9]*)(\\.(0|[1-9][0-9]*)){2}$"
          },

      "comments":
          { "description": "An array of strings to fake multi-line comments"
          , "type"       : "array"
          , "items"      : { "type": "string" }
          , "minItems"   : 1
          },

      "testGroup":
          { "description": "An array of labeled test items"
          , "type"       : "array"
          , "items"      : { "$ref": "#/definitions/labeledTestItem" }
          , "minItems"   : 1
          },

      "labeledTestItem":
          { "description": "A single test or group of tests with a description"
          , "oneOf": [ { "$ref": "#/definitions/labeledTest"      }
                     , { "$ref": "#/definitions/labeledTestGroup" }
                     ]
          },

      "labeledTest":
          { "description": "A single test with a description"
          , "type"       : "object"
          , "required"   : ["description", "property"]
          , "properties" :
                { "description": { "$ref": "#/definitions/description" }
                , "comments"   : { "$ref": "#/definitions/comments"    }
                , "property"   : { "$ref": "#/definitions/property"    }
                , "expected"   : { "$ref": "#/definitions/expected"    }
                }
          },

      "labeledTestGroup":
          { "description": "A group of tests with a description"
          , "type"       : "object"
          , "required"   : ["description", "cases"]
          , "properties" :
                { "description": { "$ref": "#/definitions/description" }
                , "comments"   : { "$ref": "#/definitions/comments"    }
                , "cases"      : { "$ref": "#/definitions/testGroup"   }
                }
          , "additionalProperties": false
          },

      "description":
          { "description": "A short, clear, one-line description"
          , "type"       : "string"
          },

      "property":
          { "description": "A letters-only, lowerCamelCase property name"
          , "type"       : "string"
          , "pattern"    : "^[a-z]+([A-Z][a-z]+)*[A-Z]?$"
          },

      "expected":
          { "description": "The expected return value of a test case"
          , "properties":
               { "error": { "$ref": "#/definitions/error" }
               }
          , "dependencies":
               { "error": { "maxProperties": 1 }
               }
          },

      "error":
          { "description": "A message describing an error condition"
          , "type"       : "string"
          }

    }

}

=== exercism/problem-specifications/exercises/wordy/canonical-data.json
{
  "exercise": "wordy",
  "version": "1.2.0",
  "comments": [
    "The tests that expect 'false' should be implemented to raise",
    "an error, or indicate a failure. Implement this in a way that",
    "makes sense for your language."
  ],
  "cases": [
    {
      "description": "addition",
      "property": "answer",
      "input": {
        "question": "What is 1 plus 1?"
      },
      "expected": 2
    },
    {
      "description": "more addition",
      "property": "answer",
      "input": {
        "question": "What is 53 plus 2?"
      },
      "expected": 55
    },
    {
      "description": "addition with negative numbers",
      "property": "answer",
      "input": {
        "question": "What is -1 plus -10?"
      },
      "expected": -11
    },
    {
      "description": "large addition",
      "property": "answer",
      "input": {
        "question": "What is 123 plus 45678?"
      },
      "expected": 45801
    },
    {
      "description": "subtraction",
      "property": "answer",
      "input": {
        "question": "What is 4 minus -12?"
      },
      "expected": 16
    },
    {
      "description": "multiplication",
      "property": "answer",
      "input": {
        "question": "What is -3 multiplied by 25?"
      },
      "expected": -75
    },
    {
      "description": "division",
      "property": "answer",
      "input": {
        "question": "What is 33 divided by -3?"
      },
      "expected": -11
    },
    {
      "description": "multiple additions",
      "property": "answer",
      "input": {
        "question": "What is 1 plus 1 plus 1?"
      },
      "expected": 3
    },
    {
      "description": "addition and subtraction",
      "property": "answer",
      "input": {
        "question": "What is 1 plus 5 minus -2?"
      },
      "expected": 8
    },
    {
      "description": "multiple subtraction",
      "property": "answer",
      "input": {
        "question": "What is 20 minus 4 minus 13?"
      },
      "expected": 3
    },
    {
      "description": "subtraction then addition",
      "property": "answer",
      "input": {
        "question": "What is 17 minus 6 plus 3?"
      },
      "expected": 14
    },
    {
      "description": "multiple multiplication",
      "property": "answer",
      "input": {
        "question": "What is 2 multiplied by -2 multiplied by 3?"
      },
      "expected": -12
    },
    {
      "description": "addition and multiplication",
      "property": "answer",
      "input": {
        "question": "What is -3 plus 7 multiplied by -2?"
      },
      "expected": -17
    },
    {
      "description": "multiple division",
      "property": "answer",
      "input": {
        "question": "What is -12 divided by 2 divided by -3?"
      },
      "expected": 2
    },
    {
      "description": "unknown operation",
      "property": "answer",
      "input": {
        "question": "What is 52 cubed?"
      },
      "expected": false
    },
    {
      "description": "Non math question",
      "property": "answer",
      "input": {
        "question": "Who is the President of the United States?"
      },
      "expected": false
    }
  ]
}

=== exercism/problem-specifications/exercises/diffie-hellman/canonical-data.json
{ "exercise": "diffie-hellman"
, "version" : "1.0.0"
, "comments":
    [ " In the following descriptions, p and g represent two          "
    , " prime numbers.                                                "
    , "                                                               "
    , " Unless specified otherwise, tests are setup with              "
    , " new DiffieHellman object using p = 23; g = 5.                 "
    , "                                                               "
    , " Alice's private key = 6                                       "
    , " Alice's public key = 8                                        "
    , "                                                               "
    , " Bob's private key = 15                                        "
    , " Bob's public key = 19                                         "
    ]
, "cases":
    [ { "description": "Private keys are generated in Range (1..p)"
      , "property"   : "generatePrivateKey"
      , "p": "23"
      }
    , { "description": "generatePrivateKey's output is random."
      , "property"   : "generatePrivateKey"
      }
    , { "description": "Public key is correctly calculated from private key and two primes."
      , "property"   : "getPublicKeyFromPrivateKey"
      , "p": "23"
      , "g": "5"
      , "private_key": "6"
      , "expected": "8"
      }
    , { "description": "Shared secret is correctly calculated."
      , "property"   : "generateSharedSecret"
      , "p": "23"
      , "bob_public_key": "19"
      , "alice_private_key": "6"
      , "expected": "2"
      }
    , { "description": "Shared secret generated by Alice and Bob should be equal."
      , "property"   : "generateSharedSecret"
      }
    , { "description": "Boundary tests."
      , "cases":
          [ { "description": "Fails when the constructor arguments are out of range."
            , "property"   : "new"
            , "p"  : "0"
            , "g"   : "9999"
            , "expected"   : { "error": "Constructor arguments are out of range or non-prime!" }
            }
          , { "description": "Fails when the constructor arguments are not prime."
            , "property"   : "new"
            , "p"  : "10"
            , "g"   : "13"
            , "expected"   : { "error": "Constructor arguments are out of range or non-prime!" }
            }
          , { "description": "Fails when private key is negative."
            , "property"   : "getPublicKeyFromPrivateKey"
            , "private_key" : "-1"
            , "expected"   : { "error": "Private key must be greater than one but less than modulus parameter p!" }
            }
          , { "description": "Fails when private key is 0."
            , "property"   : "getPublicKeyFromPrivateKey"
            , "private_key" : "0"
            , "expected"   : { "error": "Private key must be greater than one but less than modulus parameter p!" }
            }
          , { "description": "Fails when private key is 1."
            , "property"   : "getPublicKeyFromPrivateKey"
            , "private_key" : "1"
            , "expected"   : { "error": "Private key must be greater than one but less than modulus parameter p!" }
            }
          , { "description": "Fails when private key is greater than the modulus parameter p."
            , "property"   : "getPublicKeyFromPrivateKey"
            , "private_key" : "p + 1"
            , "expected"   : { "error": "Private key must be greater than one but less than modulus parameter p!" }
            }
          ]
      }
    , { "description": "Optional tests with very large primes."
      , "cases":
          [ { "description": "Private keys are generated in Range (1..p)"
            , "property": "generatePrivateKey"
            , "p": "120227323036150778550155526710966921740030662694578947298423549235265759593711587341037426347114541533006628856300552706996143592240453345642869233562886752930249953227657883929905072620233073626594386072962776144691433658814261874113232461749035425712805067202910389407991986070558964461330091797026762932543"
            }
          , { "description": "Public key is correctly calculated from private key and two primes."
            , "property": "getPublicKeyFromPrivateKey"
            , "p": "120227323036150778550155526710966921740030662694578947298423549235265759593711587341037426347114541533006628856300552706996143592240453345642869233562886752930249953227657883929905072620233073626594386072962776144691433658814261874113232461749035425712805067202910389407991986070558964461330091797026762932543"
            , "g": "75205441154357919442925546169208711235485855904969178206313309299205868312399046149367516336607966149689640419216591714331722664409474612463910928128055994157922930443733535659848264364106037925315974095321112757711756912144137705613776063541350548911512715512539186192176020596861210448363099541947258202188"
            , "private_key": "8675309"
            , "expected": "81945102766205597052444239927191366879878802281637258134656723311532689587789695879960502348293388789700383121890410484395608064685866057972603193444399431765316092443741213175747052166212523610645396217140238838864033970876203333493173215068467082830013531737232331628864212666452277691016389511356912249174"
            }
          , { "description": "Shared secret is correctly calculated."
            , "property": "generateSharedSecret"
            , "p": "120227323036150778550155526710966921740030662694578947298423549235265759593711587341037426347114541533006628856300552706996143592240453345642869233562886752930249953227657883929905072620233073626594386072962776144691433658814261874113232461749035425712805067202910389407991986070558964461330091797026762932543"
            , "bob_public_key": "75205441154357919442925546169208711235485855904969178206313309299205868312399046149367516336607966149689640419216591714331722664409474612463910928128055994157922930443733535659848264364106037925315974095321112757711756912144137705613776063541350548911512715512539186192176020596861210448363099541947258202188"
            , "alice_private_key": "2483479393625932939911081304356888505153797135447327501792696199190469015215177630758617902200417377685436170904594686456961202706692908603181062371925882"
            , "expected": "70900735223964890815905879227737819348808518698920446491346508980461201746567735331455825644429877946556431095820785835497384849778344216981228226252639932672153547963980483673419756271345828771971984887453014488572245819864454136618980914729839523581263886740821363010486083940557620831348661126601106717071"
            }
          ]
      }
  ]
}

=== exercism/problem-specifications/exercises/minesweeper/canonical-data.json
{
  "exercise": "minesweeper",
  "version": "1.2.0",
  "comments": [
    " The expected outputs are represented as arrays of strings to   ",
    " improve readability in this JSON file.                         ",
    " Your track may choose whether to present the input as a single ",
    " string (concatenating all the lines) or as the list.           "
  ],
  "cases": [
    {
      "description": "no rows",
      "property": "annotate",
      "input": {
        "minefield": []
      },
      "expected": []
    },
    {
      "description": "no columns",
      "property": "annotate",
      "input": {
        "minefield": [
          "++",
          "++"
        ]
      },
      "expected": [
        "++",
        "++"
      ]
    },
    {
      "description": "no mines",
      "property": "annotate",
      "input": {
        "minefield": [
          "+---+",
          "|   |",
          "|   |",
          "|   |",
          "+---+"
        ]
      },
      "expected": [
        "+---+",
        "|   |",
        "|   |",
        "|   |",
        "+---+"
      ]
    },
    {
      "description": "minefield with only mines",
      "property": "annotate",
      "input": {
        "minefield": [
          "+---+",
          "|***|",
          "|***|",
          "|***|",
          "+---+"
        ]
      },
      "expected": [
        "+---+",
        "|***|",
        "|***|",
        "|***|",
        "+---+"
      ]
    },
    {
      "description": "mine surrounded by spaces",
      "property": "annotate",
      "input": {
        "minefield": [
          "+---+",
          "|   |",
          "| * |",
          "|   |",
          "+---+"
        ]
      },
      "expected": [
        "+---+",
        "|111|",
        "|1*1|",
        "|1*1|",
        "+---+"
      ]
    },
    {
      "description": "space surrounded by mines",
      "property": "annotate",
      "input": {
        "minefield": [
          "+---+",
          "|***|",
          "|***|",
          "|***|",
          "+---+"
        ]
      },
      "expected": [
        "+---+",
        "|***|",
        "|*8*|",
        "|***|",
        "+---+"
      ]
    },
    {
      "description": "horizontal line",
      "property": "annotate",
      "input": {
        "minefield": [
          "+-----+",
          "| * * |",
          "+-----+"
        ]
      },
      "expected": [
        "+-----+",
        "|1*2*1|",
        "+-----+"
      ]
    },
    {
      "description": "horizontal line, mines at edges",
      "property": "annotate",
      "input": {
        "minefield": ["*   *"]
      },
      "expected": ["*1 1*"]
    },
    {
      "description": "vertical line",
      "property": "annotate",
      "input": {
        "minefield": [
          "+-+",
          "| |",
          "|*|",
          "| |",
          "|*|",
          "| |",
          "+-+"
        ]
      },
      "expected": [
        "+-+",
        "|1|",
        "|*|",
        "|2|",
        "|*|",
        "|1|",
        "+-+"
      ]
    },
    {
      "description": "vertical line, mines at edges",
      "property": "annotate",
      "input": {
        "minefield": [
          "+-+",
          "|*|",
          "| |",
          "| |",
          "| |",
          "|*|",
          "+-+"
        ]
      },
      "expected": [
        "+-+",
        "|*|",
        "|1|",
        "| |",
        "|1|",
        "|*|",
        "+-+"
      ]
    },
    {
      "description": "cross",
      "property": "annotate",
      "input": {
        "minefield": [
          "+-----+",
          "|  *  |",
          "|  *  |",
          "|*****|",
          "|  *  |",
          "|  *  |",
          "+-----+"
        ]
      },
      "expected": [
        "+-----+",
        "| 2*2 |",
        "|25*52|",
        "|*****|",
        "|25*52|",
        "| 2*2 |",
        "+-----+"
      ]
    },
    {
      "description": "large minefield",
      "property": "annotate",
      "input": {
        "minefield": [
          "+------+",
          "| *  * |",
          "|  *   |",
          "|    * |",
          "|   * *|",
          "| *  * |",
          "|      |",
          "+------+"
        ]
      },
      "expected": [
        "+------+",
        "|1*22*1|",
        "|12*322|",
        "| 123*2|",
        "|112*4*|",
        "|1*22*2|",
        "|111111|",
        "+------+"
      ]
    }
  ]
}

=== exercism/problem-specifications/exercises/yacht/canonical-data.json
{
    "exercise" : "yacht",
    "version" : "1.0.0",
    "comments" : [
        "The dice are represented always as a list of exactly five integers",
        "with values beteen 1 and 6 inclusive. The category is an integer.",
        "the numbers 0 to 5 represent the categories 'ones' to 'sixes'",
        "Then 6 is full house,",
        "     7 is four of a kind",
        "     8 is a little straight 1-5",
        "     9 is b big straight 2-6",
        "    10 is Choise, sometimes called Chance",
        "    11 is Yacht, or five of a kind"
    ],
    "cases": [
	{
	
        "description": "Yacht",
        "property":    "score",
        "input":       {
		    "dice":    [5, 5, 5, 5, 5],
		    "category":11
        },
		"expected":    50
	},
	{
		"description": "Not Yacht",
        "property":    "score",
        "input":       {
		    "dice":    [1, 3, 3, 2, 5],
		    "category":11
        },
		"expected":    0
	},
	{
		"description": "Ones",
        "property":    "score",
        "input":       {
		    "dice":    [1, 1, 1, 3, 5],
		    "category":0
        },
		"expected":    3
	},
	{
		"description": "Ones, out of order",
        "property":    "score",
        "input":       {
		    "dice":    [3, 1, 1, 5, 1],
		    "category":0
        },
		"expected":    3
	},
	{
		"description": "No ones",
        "property":    "score",
        "input":       {
		    "dice":    [4, 3, 6, 5, 5],
		    "category":0
        },
		"expected":    0
	},
	{
		"description": "Fours",
        "property":    "score",
        "input":       {
		    "dice":    [1, 4, 1, 4, 1],
		    "category":3
        },
		"expected":    8
	},
	{
		"description": "Yacht counted as threes",
        "property":    "score",
        "input":       {
		    "dice":    [3, 3, 3, 3, 3],
		    "category":2
        },
		"expected":    15
	},
	{
		"description": "Yacht of 3s counted as fives",
        "property":    "score",
        "input":       {
		    "dice":    [3, 3, 3, 3, 3],
		    "category":4
        },
		"expected":    0
	},
	{
		"description": "Full house",
        "property":    "score",
        "input":       {
		    "dice":    [2, 2, 4, 4, 4],
		    "category":6
        },
		"expected":    16
	},
	{
		"description": "Full house unsorted",
        "property":    "score",
        "input":       {
		    "dice":    [5, 3, 3, 5, 3],
		    "category":6
        },
		"expected":    19
	},
	{
		"description": "Not a full house",
        "property":    "score",
        "input":       {
		    "dice":    [2, 2, 4, 4, 5],
		    "category":6
        },
		"expected":    0
	},
	{
		"description": "Yacht is not a full house",
        "property":    "score",
        "input":       {
		    "dice":    [2, 2, 2, 2, 2],
		    "category":6
        },
		"expected":    0
	},
	{
		"description": "Four of a Kind",
        "property":    "score",
        "input":       {
		    "dice":    [1, 2, 2, 2, 2],
		    "category":7
        },
		"expected":    8
	},
	{
		"description": "Four of a Kind unsorted",
        "property":    "score",
        "input":       {
		    "dice":    [6, 6, 4, 6, 6],
		    "category":7
        },
		"expected":    24
	},
	{
		"description": "Yacht can be scored as Four of a Kind",
        "property":    "score",
        "input":       {
		    "dice":    [3, 3, 3, 3, 3],
		    "category":7
        },
		"expected":    12
	},
	{
		"description": "Not Four of a Kind",
        "property":    "score",
        "input":       {
		    "dice":    [3, 3, 3, 5, 5],
		    "category":7
        },
		"expected":    0
	},
	{
		"description": "Little Straight",
        "property":    "score",
        "input":       {
		    "dice":    [1, 2, 3, 4, 5],
		    "category":8
        },
		"expected":    30
	},
	{
		"description": "Little Straight unsorted",
        "property":    "score",
        "input":       {
		    "dice":    [3, 5, 4, 1, 2],
		    "category":8
        },
		"expected":    30
	},
	{
		"description": "Little Straight as Big Straight",
        "property":    "score",
        "input":       {
		    "dice":    [1, 2, 3, 4, 5],
		    "category":9
        },
		"expected":    0
	},
	{
		"description": "Not a little straight",
        "property":    "score",
        "input":       {
		    "dice":[1, 2, 3, 4, 6],
		    "category":8
        },
		"expected":    0
	},
	{
		"description": "Big Straight",
        "property":    "score",
        "input":       {
		    "dice":    [2, 3, 4, 5, 6],
		    "category":9
        },
		"expected":    30
	},
	{
		"description": "Big Straight unsorted",
        "property":    "score",
        "input":       {
		    "dice":    [4, 6, 2, 5, 3],
		    "category":9
        },
		"expected":    30
	},
	{
		"description": "Big Straight as little straight",
        "property":    "score",
        "input":       {
		    "dice":    [6, 5, 4, 3, 2],
		    "category":8
        },
		"expected":    0
	},
	{
		"description": "Choice",
        "property":    "score",
        "input":       {
		    "dice":    [3, 3, 5, 6, 6],
		    "category":10
        },
		"expected":    23
	},
	{
		"description": "Yacht as choice",
        "property":    "score",
        "input":       {
		    "dice":    [2, 2, 2, 2, 2],
		    "category":10
        },
		"expected":    10
	},
	{
		"description": "Big Straight as Choice",
        "property":    "score",
        "input":       {
		    "dice":    [2, 3, 4, 5, 6],
		    "category":10
        },
		"expected":    20
	},
	{
		"description": "Full House as choice",
        "property":    "score",
        "input":       {
		    "dice":    [1, 1, 1, 6, 6],
		    "category":10
        },
		"expected":    15
	}
    ]
}
